# Generated by Django 5.0.7 on 2025-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="TOKEN",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "管理员"),
                            ("vip", "VIP用户"),
                            ("user", "普通用户"),
                            ("illegal_user", "非法用户"),
                        ],
                        default="user",
                        max_length=32,
                        verbose_name="角色",
                    ),
                ),
            ],
        ),
    ]
