# Generated by Django 5.0.7 on 2025-01-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SDTasks", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paraminfo",
            name="Param",
            field=models.CharField(max_length=64, verbose_name="参数"),
        ),
        migrations.CreateModel(
            name="ImgInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_path", models.CharField(max_length=10000, verbose_name="图片")),
                (
                    "img_type",
                    models.CharField(
                        choices=[("txt_to_img", "文生图"), ("img_to_img", "图生图")],
                        max_length=64,
                        verbose_name="图片类型",
                    ),
                ),
                (
                    "img_name",
                    models.CharField(
                        default="", max_length=1000, verbose_name="图片名称"
                    ),
                ),
                ("desc", models.TextField(default="", verbose_name="描述信息")),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.userinfo",
                    ),
                ),
            ],
        ),
    ]
