# Generated by Django 5.0.7 on 2025-01-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SDTasks", "0002_alter_paraminfo_param_imginfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="imginfo",
            name="img_logo",
            field=models.BinaryField(
                max_length=10000, null=True, verbose_name="图片缩略图"
            ),
        ),
        migrations.AlterField(
            model_name="imginfo",
            name="img_path",
            field=models.CharField(max_length=10000, verbose_name="图片地址"),
        ),
        migrations.AlterField(
            model_name="imginfo",
            name="img_type",
            field=models.CharField(
                choices=[("txt_to_img", "文生图"), ("img_to_img", "图生图")],
                default="txt_to_img",
                max_length=64,
                verbose_name="图片类型",
            ),
        ),
    ]
