# Generated by Django 5.0.7 on 2025-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SDTasks", "0003_imginfo_img_logo_alter_imginfo_img_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imginfo",
            name="img_status",
            field=models.CharField(
                choices=[("pending", "正在生图"), ("success", "生图完成")],
                default="pending",
                max_length=1000,
                verbose_name="图片状态",
            ),
        ),
        migrations.AddField(
            model_name="imginfo",
            name="task_id",
            field=models.TextField(null=True, verbose_name="任务ID"),
        ),
        migrations.AlterField(
            model_name="imginfo",
            name="desc",
            field=models.TextField(null=True, verbose_name="描述信息"),
        ),
        migrations.AlterField(
            model_name="imginfo",
            name="img_name",
            field=models.CharField(max_length=1000, null=True, verbose_name="图片名称"),
        ),
        migrations.AlterField(
            model_name="imginfo",
            name="img_path",
            field=models.CharField(
                max_length=10000, null=True, verbose_name="图片地址"
            ),
        ),
    ]
