# Generated by Django 5.0.7 on 2025-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SDTasks", "0004_imginfo_img_status_imginfo_task_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imginfo",
            name="img_status",
            field=models.CharField(
                choices=[
                    ("pending", "正在生图"),
                    ("success", "生图完成"),
                    ("failure", "生图失败"),
                ],
                default="pending",
                max_length=1000,
                verbose_name="图片状态",
            ),
        ),
    ]
